### ISSUE TITLE
To create the fatfs image on linux (or you have to make the code here work and build for your OS). 

### ISSUE THREAD

**Issue by HarpreetHeera** [marcmerlin/esp32_fatfsimage#1]
Hi,
Sorry for asking this in issue section. 

But how to make fatfs image using MINGW32 commandline interface in windows10? I tried https://github.com/jkearins/ESP32_mkfatfs and succeeded in making fatfs image file of 3008 KB by changing FATFS size and starting address and I also replace "Partition.csv" with " noota_3gffat.csv " and renamed but after transferring it to ESP32 and checking on serial monitor it shows " failed to mount." 

I tried https://github.com/lorol/arduino-esp32fs-plugin tool using arduino IDE. 
By selecting option FATFS and selecting upload - it also shows "String index out of range: -1" error in Arduino IDE.

I am only able to flash and mount successfully img.ffat that was build by Marcmerlin. 

Sorry for my little knowledge in this regards but it's been so many days I am still trying with no luck.

Any help to proceed further will be appreciated.

Thanks

**Comment by HarpreetHeera** [comment]
Hi again,
What Should be the sector size in the following? I found this in sdkconfig. 
#
# Wear Levelling
#
CONFIG_WL_SECTOR_SIZE_512=y
CONFIG_WL_SECTOR_SIZE_4096=
CONFIG_WL_SECTOR_SIZE=512
CONFIG_WL_SECTOR_MODE_PERF=
CONFIG_WL_SECTOR_MODE_SAFE=y
CONFIG_WL_SECTOR_MODE=1

**Comment by marcmerlin** [comment]
I'm not sure if I fully understand your question. I build my image like this:
https://github.com/marcmerlin/AnimatedGIFs/blob/master/Makefile

```
	fatfsimage img3.ffat 3008 data/
```

For things to work, you need to configure your arduino IDE so that it does create a flash layout with FatFS
That is using the linux binary. I have not tried to rebuild the binary myself.
Then, indeed the partition layout you are using must be exactly the same  size as the 3008 number above or things won't work.

As for https://github.com/lorol/arduino-esp32fs-plugin , it did not support FatFS when I needed it. It looks like it does now, so you probably want to use this instead of my solution which was a stopgap, at best.

**Comment by HarpreetHeera** [comment]
Thank you so much for quick reply.
Please confirm, Do I need Linux OS to run "fatfsimage img3.ffat 3008 data/ " command?  Where to run this command? 
I am using windows 10 and msys32 (mingw32.exe console) to run the "make " commands and  
In cmd.exe window I run "C:\>esptool.py --chip esp32 --port COM9 --baud 921600 write_flash  0x110000 img.ffat" command to write image to esp32 chip.

Please let me know is it possible to create fatfs image using windows10 ? I copied files "esp32fs.jar, mkfatfs.exe in Arduino/tool folder and also update partition tables successfully. Please guide me how to configure Arduino IDE? I am unable to figure out how to generate fatfs image file of my custom gifs.

Sorry I am asking asking dumb things. hope you bear me.

Thanks

**Comment by marcmerlin** [comment]
Sorry, I can't help you with building on windows, I don't use windows.
fatfsimage is indeed a linux binary. there is source to rebuild it, but you're on your own for that.

As I said, https://github.com/lorol/arduino-esp32fs-plugin  will probably help you better since I think it's all in java and will probably work for you

**Comment by HarpreetHeera** [comment]
Thanks Marcmerlin,
I will post here If I figure out making fatfs image on Windows OS.

Thanks for your quick reply.

**Comment by HarpreetHeera** [comment]
Thanks for your support and advice. 

https://github.com/lorol/arduino-esp32fs-plugin worked in windows. It uploaded the gif data to FATFS partition using Arduino IDE plugin.

Thanks

**Comment by marcmerlin** [comment]
I've updated my repo to point to the newer plugin
